### 8-5-1. 다중 catch

try 블록 내부는 다양한 예외가 발생할 수 있음. 예외별로 다른 예외 처리 코드를 사용하기 위해 `다중 catch 블록`을 작성할 수 있음. try블록에서 동시 다발적으로 예외가 발생하지 않고 하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문임.